[tools]
python = "3.13"

[env]
_.python.venv = { path = ".venv", create = true }
SAMPLE = "Hello, sample!"

[tasks.show-tools-extract_audio_info-audee]
description = "audio_info_extractorのチェック用（audee）"
run = '''
python -m tools.extract_audio_info tests/private_data/test_audee_page.html --domain audee.jp
'''

[tasks.show-tools-extract_audio_info-bitfan]
description = "audio_info_extractorのチェック用（bitfan）"
run = '''
python -m tools.extract_audio_info tests/private_data/test_bitfan_page.html --domain bitfan.net
'''

[tasks.tools-extract_audio_info]
usage = '''
arg "htmlfile" help="htmlファイルを指定"
flag "--domain <domain>" help="ドメインを指定"
'''
alias = "teai"
run = "python tools/extract_audio_info.py ${usage_htmlfile} ${usage_domain}"

[tasks.save-book-for-kindle]
description = "Kindleの本を撮影してPDF化します"
alias = "sbk"
usage = '''
arg "output_dir" help="PDFの出力先ディレクトリを指定"
flag "--pages <pages>" help="撮影するページ数を指定"
flag "--auto-stop" help="ページの最後に到達した際に自動で撮影を停止"
flag "--quality <quality>" help="出力PDFの画質を指定(high, medium, low)"
'''
run = '''
#!/bin/bash
set -euo pipefail

# --outputは必須引数
cmd=("python" "save_book_for_kindle.py" "--output" "${usage_output_dir:?output_dir is required}")

# --pagesが指定されていれば追加
if [[ -n "${usage_pages:-}" ]]; then
  cmd+=("--pages" "${usage_pages}")
fi

# --auto-stopが指定されていれば追加
if [[ -n "${usage_auto_stop:-}" ]]; then
  cmd+=("--auto-stop")
fi

# --qualityが指定されていれば追加
if [[ -n "${usage_quality:-}" ]]; then
  cmd+=("--quality" "${usage_quality}")
fi

# 組み立てたコマンドを実行
exec "${cmd[@]}"
'''
